project:
  type: website

website:
  title: "Maykon Pedro"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
format:
  html:
    theme:
      - Flatly
      - brand
    css: styles.css

execute:
  freeze: auto

comments:
  giscus: 
    repo: maykongpedro/maykon_pedro_quarto_blog

