[project]
name = "20260105-o-problema-do-poeta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "highspy>=1.12.0",
    "jupyter>=1.1.1",
    "pyomo>=6.9.5",
]
